// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickemBot.Data;

#nullable disable

namespace PickemBot.Migrations
{
    [DbContext(typeof(PickemContext))]
    [Migration("20221101150915_add champion table")]
    partial class addchampiontable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ChallengerPicksTeam", b =>
                {
                    b.Property<int>("AdvanceTeamsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickedByChallengerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdvanceTeamsID", "PickedByChallengerID");

                    b.HasIndex("PickedByChallengerID");

                    b.ToTable("ChallengerPicksTeam");
                });

            modelBuilder.Entity("ChampionPicksTeam", b =>
                {
                    b.Property<int>("PickedQuarterFinalsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuarterFinalistsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PickedQuarterFinalsID", "QuarterFinalistsID");

                    b.HasIndex("QuarterFinalistsID");

                    b.ToTable("ChampionPicksTeam");
                });

            modelBuilder.Entity("ChampionPicksTeam1", b =>
                {
                    b.Property<int>("PickedSemiFinalsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemiFinalistsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PickedSemiFinalsID", "SemiFinalistsID");

                    b.HasIndex("SemiFinalistsID");

                    b.ToTable("ChampionPicksTeam1");
                });

            modelBuilder.Entity("LegendPicksTeam", b =>
                {
                    b.Property<int>("AdvanceTeamsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickedByLegendID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdvanceTeamsID", "PickedByLegendID");

                    b.HasIndex("PickedByLegendID");

                    b.ToTable("LegendPicksTeam");
                });

            modelBuilder.Entity("PickemBot.Models.ChallengerPicks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoWinID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UndefeatedID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("NoWinID");

                    b.HasIndex("UndefeatedID");

                    b.ToTable("ChallengerPicks");
                });

            modelBuilder.Entity("PickemBot.Models.ChampionPicks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WinnerID");

                    b.ToTable("ChampionPicks");
                });

            modelBuilder.Entity("PickemBot.Models.LegendPicks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoWinID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UndefeatedID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("NoWinID");

                    b.HasIndex("UndefeatedID");

                    b.ToTable("LegendPicks");
                });

            modelBuilder.Entity("PickemBot.Models.Picker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChallengerPicksID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChampionPicksID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LegendPicksID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ChallengerPicksID");

                    b.HasIndex("ChampionPicksID");

                    b.HasIndex("LegendPicksID");

                    b.ToTable("Pickers");
                });

            modelBuilder.Entity("PickemBot.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmoteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ChallengerPicksTeam", b =>
                {
                    b.HasOne("PickemBot.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("AdvanceTeamsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickemBot.Models.ChallengerPicks", null)
                        .WithMany()
                        .HasForeignKey("PickedByChallengerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChampionPicksTeam", b =>
                {
                    b.HasOne("PickemBot.Models.ChampionPicks", null)
                        .WithMany()
                        .HasForeignKey("PickedQuarterFinalsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickemBot.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("QuarterFinalistsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChampionPicksTeam1", b =>
                {
                    b.HasOne("PickemBot.Models.ChampionPicks", null)
                        .WithMany()
                        .HasForeignKey("PickedSemiFinalsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickemBot.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("SemiFinalistsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegendPicksTeam", b =>
                {
                    b.HasOne("PickemBot.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("AdvanceTeamsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickemBot.Models.LegendPicks", null)
                        .WithMany()
                        .HasForeignKey("PickedByLegendID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PickemBot.Models.ChallengerPicks", b =>
                {
                    b.HasOne("PickemBot.Models.Team", "NoWin")
                        .WithMany()
                        .HasForeignKey("NoWinID");

                    b.HasOne("PickemBot.Models.Team", "Undefeated")
                        .WithMany()
                        .HasForeignKey("UndefeatedID");

                    b.Navigation("NoWin");

                    b.Navigation("Undefeated");
                });

            modelBuilder.Entity("PickemBot.Models.ChampionPicks", b =>
                {
                    b.HasOne("PickemBot.Models.Team", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("PickemBot.Models.LegendPicks", b =>
                {
                    b.HasOne("PickemBot.Models.Team", "NoWin")
                        .WithMany()
                        .HasForeignKey("NoWinID");

                    b.HasOne("PickemBot.Models.Team", "Undefeated")
                        .WithMany()
                        .HasForeignKey("UndefeatedID");

                    b.Navigation("NoWin");

                    b.Navigation("Undefeated");
                });

            modelBuilder.Entity("PickemBot.Models.Picker", b =>
                {
                    b.HasOne("PickemBot.Models.ChallengerPicks", "ChallengerPicks")
                        .WithMany()
                        .HasForeignKey("ChallengerPicksID");

                    b.HasOne("PickemBot.Models.ChampionPicks", "ChampionPicks")
                        .WithMany()
                        .HasForeignKey("ChampionPicksID");

                    b.HasOne("PickemBot.Models.LegendPicks", "LegendPicks")
                        .WithMany()
                        .HasForeignKey("LegendPicksID");

                    b.Navigation("ChallengerPicks");

                    b.Navigation("ChampionPicks");

                    b.Navigation("LegendPicks");
                });
#pragma warning restore 612, 618
        }
    }
}
